included:
  - brd-ios/breadwallet/

disabled_rules:
  - trailing_whitespace
  - identifier_name
  - large_tuple
  - weak_delegate
  - todo
  - comment_spacing
  - inclusive_language

opt_in_rules:
  - empty_count
  - empty_string
  - multiline_parameters

excluded:
  - Modules
  - breadwalletTests
  - breadwalletUITests
  - breadwallet/src/Constants/Strings.swift
  - breadwallet/*.pb.swift # ProtoBuf generated files

line_length:
    warning: 170
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 300
    error: 500
function_parameter_count:
    warning: 6
    error: 8
type_body_length:
    warning: 400
    error: 600
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 15
    error: 25
    ignores_case_statements: true
nesting:
    type_level: 2
    function_level: 5
type_name:
    max_length: 50 #warning
    excluded:
    - T
    - U
    - I
    - DS
    - VM
    - C
    - P

reporter: "xcode"
