#!/bin/zsh

if [[ $(uname -m) != 'arm64' ]]; then
    echo "Running on X86"
    exit 0
fi

echo "Running on ARM"

ARM="ios-arm64"
COSMOS="Cosmos"

ARM_SIMULATOR="$ARM-simulator"
X86_SIMULATOR="ios-x86_64-simulator"
FAT_SIMULATOR="fat-simulator"

COSMOS_FRAMEWORK="$COSMOS.framework"
INFO_PLIST="Info.plist"

FRAMEWORK_PATH="brd-ios/Frameworks/$COSMOS.xcframework"
FRAMEWORK_BIN_PATH="$FRAMEWORK_PATH/$ARM_SIMULATOR/$COSMOS_FRAMEWORK/$COSMOS"
FRAMEWORK_PATH_PLIST="$FRAMEWORK_PATH/$COSMOS_FRAMEWORK"
FRAMEWORK_PATH_ARM_PLIST="$FRAMEWORK_PATH/$ARM_SIMULATOR/$COSMOS_FRAMEWORK/$INFO_PLIST"

ARM_SIMULATOR_PATH="$FRAMEWORK_PATH/$ARM_SIMULATOR"

X86_BINARY_PATH="$FRAMEWORK_PATH/$X86_SIMULATOR/$COSMOS_FRAMEWORK/$COSMOS"
ARM_BINARY_PATH="$FRAMEWORK_PATH/$ARM_SIMULATOR/$COSMOS_FRAMEWORK/$COSMOS"
FAT_BINARY_PATH="$FRAMEWORK_PATH/$FAT_SIMULATOR/"

MODIFICATION_INDICATOR="modified_cosmos_dir_do_not_delete.txt"

if [ -f $FRAMEWORK_PATH/$MODIFICATION_INDICATOR ]; then
    echo "Framework has already been modified for ARM devices."
    exit 0
fi


cp -r $FRAMEWORK_PATH/$ARM $ARM_SIMULATOR_PATH

xcrun vtool -arch arm64 \
            -set-build-version 7 12.0 12.0 \
            -replace \
            -output "$FRAMEWORK_BIN_PATH.updated" \
            $FRAMEWORK_BIN_PATH

rm $FRAMEWORK_BIN_PATH
mv "$FRAMEWORK_BIN_PATH.updated" $FRAMEWORK_BIN_PATH

xcrun codesign --sign - $FRAMEWORK_BIN_PATH

mkdir -p "$FAT_BINARY_PATH"
cp -r "$FRAMEWORK_PATH/$X86_SIMULATOR/" "$FAT_BINARY_PATH"
rm -f "$FRAMEWORK_PATH/$FAT_SIMULATOR/$COSMOS_FRAMEWORK/$COSMOS"

lipo -create -output "$FAT_BINARY_PATH/$COSMOS_FRAMEWORK/$COSMOS" $ARM_BINARY_PATH $X86_BINARY_PATH

rm -r -f "$FRAMEWORK_PATH/$X86_SIMULATOR/"
rm -r -f "$ARM_SIMULATOR_PATH"
mv "$FAT_BINARY_PATH" "$FRAMEWORK_PATH/$X86_SIMULATOR"

touch $FRAMEWORK_PATH/$MODIFICATION_INDICATOR
